language: generic

sudo: required
  services:
    - docker
  
before_install:
  - docker build -t joshbarnes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joshbarnes/docker-react npm run test
